---
- hosts: all
  become: yes
  tasks:
    - name: Update apt
      apt: update_cache=yes

    - name: Delete default eth0
      shell: ip route del default dev eth0
    - name: Add default eth1
      shell: ip route add default via 192.168.0.1 dev eth1    
